{
  "artifacts": [],
  "command": "my_main",
  "experiment": {
    "base_dir": "/Users/miguelferreira/PycharmProjects/AASMA/epymarl/src",
    "dependencies": [
      "munch==2.5.0",
      "numpy==1.22.4",
      "PyYAML==5.3.1",
      "sacred==0.8.2",
      "torch==1.11.0"
    ],
    "mainfile": "main.py",
    "name": "pymarl",
    "repositories": [
      {
        "commit": "3d1463de723fd4cc1256244c0dd2d39b9276048a",
        "dirty": true,
        "url": "https://github.com/uoe-agents/epymarl"
      },
      {
        "commit": "3d1463de723fd4cc1256244c0dd2d39b9276048a",
        "dirty": true,
        "url": "https://github.com/uoe-agents/epymarl"
      },
      {
        "commit": "3d1463de723fd4cc1256244c0dd2d39b9276048a",
        "dirty": true,
        "url": "https://github.com/uoe-agents/epymarl"
      }
    ],
    "sources": [
      [
        "main.py",
        "_sources/main_a0a6b0acfc44b7b7bb8b698aa91dbd94.py"
      ],
      [
        "run.py",
        "_sources/run_aa05bf6e453ad6db018cc6d597ecc93b.py"
      ],
      [
        "utils/logging.py",
        "_sources/logging_8309e899ab76a4e610428ba7ee8d8acb.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/Users/miguelferreira/PycharmProjects/AASMA/venv/lib/python3.8/site-packages/sacred/config/captured_function.py\", line 42, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"src/main.py\", line 36, in my_main\n    run(_run, config, _log)\n",
    "  File \"/Users/miguelferreira/PycharmProjects/AASMA/epymarl/src/run.py\", line 55, in run\n    run_sequential(args=args, logger=logger)\n",
    "  File \"/Users/miguelferreira/PycharmProjects/AASMA/epymarl/src/run.py\", line 185, in run_sequential\n    episode_batch = runner.run(test_mode=False)\n",
    "  File \"/Users/miguelferreira/PycharmProjects/AASMA/epymarl/src/runners/parallel_runner.py\", line 104, in run\n    actions = self.mac.select_actions(self.batch, t_ep=self.t, t_env=self.t_env, bs=envs_not_terminated, test_mode=test_mode)\n",
    "  File \"/Users/miguelferreira/PycharmProjects/AASMA/epymarl/src/controllers/basic_controller.py\", line 23, in select_actions\n    chosen_actions = self.action_selector.select_action(agent_outputs[bs], avail_actions[bs], t_env, test_mode=test_mode)\n",
    "  File \"/Users/miguelferreira/PycharmProjects/AASMA/epymarl/src/components/action_selectors.py\", line 73, in select_action\n    m = Categorical(agent_inputs)\n",
    "  File \"/Users/miguelferreira/PycharmProjects/AASMA/venv/lib/python3.8/site-packages/torch/distributions/categorical.py\", line 64, in __init__\n    super(Categorical, self).__init__(batch_shape, validate_args=validate_args)\n",
    "  File \"/Users/miguelferreira/PycharmProjects/AASMA/venv/lib/python3.8/site-packages/torch/distributions/distribution.py\", line 55, in __init__\n    raise ValueError(\n",
    "ValueError: Expected parameter probs (Tensor of shape (10, 2, 5)) of distribution Categorical(probs: torch.Size([10, 2, 5])) to satisfy the constraint Simplex(), but found invalid values:\ntensor([[[nan, nan, nan, nan, nan],\n         [nan, nan, nan, nan, nan]],\n\n        [[nan, nan, nan, nan, nan],\n         [nan, nan, nan, nan, nan]],\n\n        [[nan, nan, nan, nan, nan],\n         [nan, nan, nan, nan, nan]],\n\n        [[nan, nan, nan, nan, nan],\n         [nan, nan, nan, nan, nan]],\n\n        [[nan, nan, nan, nan, nan],\n         [nan, nan, nan, nan, nan]],\n\n        [[nan, nan, nan, nan, nan],\n         [nan, nan, nan, nan, nan]],\n\n        [[nan, nan, nan, nan, nan],\n         [nan, nan, nan, nan, nan]],\n\n        [[nan, nan, nan, nan, nan],\n         [nan, nan, nan, nan, nan]],\n\n        [[nan, nan, nan, nan, nan],\n         [nan, nan, nan, nan, nan]],\n\n        [[nan, nan, nan, nan, nan],\n         [nan, nan, nan, nan, nan]]], grad_fn=<DivBackward0>)\n"
  ],
  "heartbeat": "2022-05-28T12:08:31.947561",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz",
    "hostname": "Mac-Miguel",
    "os": [
      "Darwin",
      "macOS-10.16-x86_64-i386-64bit"
    ],
    "python_version": "3.8.8"
  },
  "meta": {
    "command": "my_main",
    "options": {
      "--beat-interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print-config": false,
      "--priority": null,
      "--queue": false,
      "--s3": null,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [
        "env_args.time_limit=500",
        "env_args.key=rware:rware-tiny-2ag-v1"
      ],
      "help": false,
      "with": true
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2022-05-28T09:35:31.506171",
  "status": "FAILED",
  "stop_time": "2022-05-28T12:08:32.166505"
}